# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
